version: '3.8'

services:
  db:
    image: postgres:14
    container_name: tcc-postgres
    environment:
      POSTGRES_USER: tcc_usr
      POSTGRES_PASSWORD: tcc_pwd
      POSTGRES_DB: tcc_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tcc-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tcc_usr -d tcc_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: tcc-mediamtx
    restart: unless-stopped
    environment:
      MTX_WEBRTCADDITIONALHOSTS: "${PUBLIC_SERVER_IP:-127.0.0.1}"
    ports:
      - "18935:1935"
      - "18554:8554"
      - "18888:8888"
      - "18889:8889"
      - "18189:18189/udp"
      - "19997:9997"
      - "19996:9996"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    networks:
      - tcc-network

  api:
    build: .
    container_name: tcc-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./recordings:/recordings
    depends_on:
      db:
        condition: service_healthy
      mediamtx:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://tcc_usr:tcc_pwd@db:5432/tcc_db
      MEDIA_MTX_HOST: http://mediamtx
      CONTROL_API_PORT: 9997
      HLS_PORT: 8888
      WEBRTC_PORT: 8889
      MEDIAMTX_API_USER: 'api-backend'
      MEDIAMTX_API_PASS: 'UMA_SENHA_FORTE_E_SECRETA_AQUI'
      SECRET_KEY: 'dev_secret_key_change_me_in_prod'
      ALGORITHM: 'HS256'
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      PUBLIC_SERVER_IP: "${PUBLIC_SERVER_IP:-127.0.0.1}"
      PUBLIC_HLS_PORT: "18888"
      PUBLIC_WEBRTC_PORT: "18889"
    networks:
      - tcc-network

  frontend:
    build:
      context: ../tcc-nvr-frontend
      dockerfile: dockerfile
    container_name: tcc-frontend
    restart: always
    ports:
      - "18080:80"
    depends_on:
      - api
    networks:
      - tcc-network

volumes:
  postgres_data:


networks:
  tcc-network:
    driver: bridge